### ISSUE TITLE
User Story: Computational Biologist / Bioinformatician

### ISSUE THREAD

**Issue by cgreene** [biothings/mygeneset.info#2]
I work on a certain process. Whenever I do an analyses, there are a set of key genes that I always want to examine. Different resources and datasets that I use rely on different gene identifiers. I end up storing the group of genes as a text file in one format. Then, for whatever dataset I'm using I convert them using biomart or similar before extracting their values from the dataset.

Wouldn't it be great if I could use a package in my programming language of choice (R or python) that would store my set of genes and return it to me with the type of identifiers that I need at the time that I need them?

**Comment by vincerubinetti** [comment]
We will definitely have an easy way to do this on the frontend. As far as doing on the backend, we might consider having as a single  endpoint to be an enhancement for later, but at the very least we'll have instructions on how to get the desired identifiers from the backend.
