### ISSUE TITLE
Query user's genesets?

### ISSUE THREAD

**Issue by vincerubinetti** [biothings/mygeneset.info#27]
In the web app, we have a browse page where you'll be able to search through all (public) by keyword and species. I'm using the current API endpoint to build that functionality.

We'll also have a page where the user sees their own personally created genesets. If the user has a lot of genesets, it may be good to have the same search by keyword and species functionality, rather than having a long list.

When we add user authentication, how will getting their genesets work? Will it be its own endpoint like `/v1/user` or will it be an extension of the existing query endpoint like `/v1/query?user=198273&q=glucose`.

**Comment by ravila4** [comment]
User genesets can be queried by the `author` filter:  `/v1/query?q=author:198273` or `/v1/query?q=author:ravila4 AND name:glucose`
