### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by vincerubinetti** [biothings/mygeneset.info#31]
Opening this issue to generally discuss the relevance of search results.

Search "NF1" and "neurofibromin 1" comes up far down the search results.

Search "tp53" and "tumor protein p53" comes up ~10th.

Exact matches often don't come up first.

**Comment by cgreene** [comment]
NRAS is apparently not in the top 100 (at least, I didn't see it scanning through)

**Comment by ravila4** [comment]
I think appending wildcards `*` to query strings is having a negative effect here.
Another downside of using wildcards is that you can't enter something like: "symbol:NF1" on the search box.

**Comment by ravila4** [comment]
It looks like this issue was fixed after removing the wildcard from query strings.
