### ISSUE TITLE
Create API query handlers for 'source' and 'author' filters

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info#39]
We would like to create two new API parameters `source=` and `author=` to filter API results. (Similar function to the `species=` parameter.)

 Currently, we support queries like this one:  https://mygeneset.info/v1/query?q=source:smpdb.

However, if we want to make a compound query, we need to use the 'AND' operator to concatenate the fielded queries, like so: https://mygeneset.info/v1/query?q=source:smpdb%20AND%20name:phosphatidylethanolamine.

Since we expect that this will be a commonly used filter, it would be useful and cleaner to have a special parameter to filter by source and author (for user genesets). e.g.:

https://mygeneset.info/v1/query?q=name:phosphatidylethanolamine&source=smpdb
https://mygeneset.info/v1/query?q=name:glucose&author=username

**Comment by ravila4** [comment]
Relevant configuration files:

https://github.com/biothings/mygeneset.info/blob/master/src/config_web.py#L69-L97
https://github.com/biothings/mygeneset.info/blob/master/src/web/pipeline.py#L39-L50

**Comment by dongbohu** [comment]
@ravila4 I can implement the `source` filter for now. Since we don't have any user-defined genesets yet, `author` filter probablay should be implemented later when these genesets are available. What do you think?

**Comment by ravila4** [comment]
@dongbohu sounds good. It would be hard to test without data, so it can wait until we have some genesets with this field.
