### ISSUE TITLE
Define a standard payload for writing and editing user genesets

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info#42]
@vincerubinetti I tried to organize the proposed fields as we discussed last week. Let me know if it looks alright.

## Creating a new geneset

**Required fields:**
| field | type   | notes                                           | default |
|-------|--------|-------------------------------------------------------|---------|
| `name`  | string |                                |         |
| `genes` | list   | my_gene, ncbi, symbol, ensembl, or uniprot ids |         |

**Optional fields:**
| field       | type   | notes         | default |
|-------------|--------|---------------------|---------|
| `description` | string |                    |         |
| `is_public`   | string |                     | True    |

**Derived fields**
| field  | type    | notes                             |
|--------|---------|-----------------------------------|
| `author` | string  | obtained from user authentication |
| `taxid`  | integer | retrieved from mygene.info        |

## Updating genesets
**Optional fields:**
| field       | type   | notes         | 
|-------------|--------|---------------------|
| `name` | string |                    |
| `description` | string |                    |
| `is_public`   | string |                     |
| `genes` | list   | my_gene, ncbi, symbol, ensembl, or uniprot ids. Overwrites previous list.|
| `add` | list   | my_gene, ncbi, symbol, ensembl, or uniprot ids  to add|
| `remove` | list   | my_gene, ncbi, symbol, ensembl, or uniprot ids to remove|

**Comment by vincerubinetti** [comment]
This looks basically like I imagined it would 👍

**Comment by ravila4** [comment]
CLosing this, user geneset creation has been implemented.
