### ISSUE TITLE
Add taxid to all genes

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info#69]
Currently taxid only exists as a toplevel field for genesets that have a single species, while multispecies genesets have a taxid field for each gene. The initial intention was to remove redundancy, but the frontend would benefit from having that extra field on every gene.

Another benefit is that it would greatly simplify some of the code on the geneset creation module.

**Comment by vincerubinetti** [comment]
The backend is not currently attaching taxid to each gene:
https://mygeneset.info/v1/geneset/D014028_9606?fields=genes

@everaldorodrigo is this a regression?

**Comment by newgene** [comment]
Reopen this issue to fixed the fixing "taxid" field for CTD data source.

**Comment by everaldorodrigo** [comment]
@vincerubinetti we made a new release and now we can see the `taxid` field in all genes.

We can see it in this query https://mygeneset.info/v1/query?q=C097256_10116&size=2. The result is below:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/5834247/210901715-d225e638-e056-41e2-89b1-a2a19a4c83fb.png">

**Comment by vincerubinetti** [comment]
Thanks! The geneset where the error was originally reported now shows 1 species:
https://mygeneset.info/geneset/D014028_9606
