### ISSUE TITLE
Requirement: Linux OS?

### ISSUE THREAD

**Issue by dongbohu** [biothings/mygeneset.info#7]
I tried to install this project on macOS but failed with this error:
```
    inotify is not available on macosx-10.9-x86_64
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
After digging deeper, I realized that this project requires `biothings.api`, whose hub component then requires `pyinotify`:
https://github.com/biothings/biothings.api/blob/faa268acdb68718ff444f53aa640051fe58366a2/setup.py#L69

And according to the wiki page of `pyinotify`:
https://github.com/seb-m/pyinotify/wiki/Install
`Linux kernel with inotify ≥ 2.6.13` is required. Should we include this dependency in our `RADME.md` file (and probably in `README.md` of `biothings.api` repo too)?

**Comment by zcqian** [comment]
We have implemented a workaround so inotify is no longer a necessity. By default we still require it on Linux, but not anymore on other platforms.
