### ISSUE TITLE
Add human-readable name to curated genesets metadata

### ISSUE THREAD

**Issue by vincerubinetti** [biothings/mygeneset.info#85]
See https://github.com/biothings/mygeneset.info-website/issues/46

https://mygeneset.info/v1/metadata

It would be nice if each entry under `src` had a `name` field with a full, human-readable name, e.g. "Disease Ontology" instead of "DO".

**Comment by newgene** [comment]
the data plugin metadata fields can include additional metadata fields if needed:

https://github.com/biothings/mygeneset.info/blob/e14100ed5b4f52cfea6b7b1a02fda0b92da0eb58/src/plugins/do/manifest.json#L4-L8
