### ISSUE TITLE
Add code examples from manuscript submission to ReadTheDocs documentation

### ISSUE THREAD

**Issue by gtsueng** [biothings/mygeneset.info#99]
The code examples can be found here: https://docs.google.com/document/d/1R964Tz8aORehmL0-8EzZsNvIOkkqp5sh9uBE6O-s8dY/edit?usp=sharing

and here: https://drive.google.com/file/d/11FPwR585h24hA71ubkmFeQ4wZAqpHCXN/view?usp=sharing

**Comment by newgene** [comment]
Created two ipynb files here (b5a7ceb43270a4467f21d0a9978d88cf59d42105):

https://github.com/biothings/mygeneset.info/blob/master/docs/ipynb/mygeneset_workflow.ipynb  (supp fig 2)
https://github.com/biothings/mygeneset.info/blob/master/docs/ipynb/mygeneset_versioning_caching.ipynb (supp fig 3)
